### ISSUE TITLE
The 'get' module downloads the file and names it the hash value

### ISSUE THREAD

**Issue by shshnkvadali** [ipfs/py-ipfs-api#110] opened 2017-10-11 20:22 UTC
With the following code
`api = ipfsapi.connect('127.0.0.1', 5001)`
`api.get(<hash>)`
The file is downloaded and is renamed as hash. I'm not certain if this is done on purpose or an issue that needs to be resolved.

**Comment by whereswaldon** [comment] 2017-10-14 15:32
That is correct behavior. This is also what the `ipfs` CLI does when you download a file by hash, unless you specify an output filename. We do not currently have that capability, though if you're interested in adding it, see #48

**Comment by lordcirth** [comment] 2019-02-02 21:30
I believe this should be closed as a duplicate of #48.

**Comment by alexander255** [comment] 2019-02-13 23:29
@lordcirth: Indeed, thanks for bumping!

**Closed by alexander255** 2019-02-13 23:29 UTC
